Repository PostGraphDB/postgraph, pull requests merged in 2023-06, with the labels that each got.

#75 id and label functions for edge datatype
  postgraph--0.0.1.sql
  regress/expected/catalog.out
  regress/expected/edge.out
  regress/expected/vertex.out
  regress/sql/edge.sql
  src/backend/utils/adt/edge.c
Labels: enhancement

#76 Implement start_id and end_id for edge datatype
  postgraph--0.0.1.sql
  regress/expected/catalog.out
  regress/expected/edge.out
  regress/sql/edge.sql
  src/backend/utils/adt/edge.c
Labels: enhancement

#77 Property Function for vertex datatype
  postgraph--0.0.1.sql
  regress/expected/catalog.out
  regress/expected/vertex.out
  regress/sql/vertex.sql
  src/backend/utils/adt/vertex.c
Labels: enhancement

#78 Implement Properties Function for Edge
  postgraph--0.0.1.sql
  regress/expected/catalog.out
  regress/expected/edge.out
  regress/sql/edge.sql
  src/backend/utils/adt/edge.c
Labels: enhancement

#83 Moved list function declarations
  postgraph--0.0.1.sql
Labels: maintenance

#84 Rename age_agtype_float8_accum
  postgraph--0.0.1.sql
  src/backend/utils/adt/agtype.c
Labels: maintenance

#85 Refactor min and max
  postgraph--0.0.1.sql
  regress/expected/expr.out
  regress/sql/expr.sql
  src/backend/utils/adt/agtype.c
Labels: maintenance

#86 Removed Apache config File
  .asf.yaml
Labels: maintenance

#91 Sqrt refactor
  postgraph--0.0.1.sql
  regress/expected/expr.out
  regress/sql/expr.sql
  src/backend/utils/adt/agtype.c
  src/backend/utils/adt/agtype_parser.c
  src/include/utils/agtype.h
Labels: enhancement, maintenance

#90 Cleanup agtype_parser
  regress/expected/expr.out
  regress/sql/expr.sql
  src/backend/utils/adt/agtype_parser.c
Labels: maintenance

#92 exp Refactor
  postgraph--0.0.1.sql
  src/backend/utils/adt/agtype.c
Labels: bug, enhancement, maintenance

#93 Refactor natural log function
  postgraph--0.0.1.sql
  regress/expected/expr.out
  src/backend/utils/adt/agtype.c
Labels: enhancement, maintenance

#94 Refactor log10
  regress/expected/expr.out
  src/backend/utils/adt/agtype.c
Labels: enhancement, maintenance

#96 Refactor size function
  src/backend/utils/adt/agtype.c
Labels: maintenance

#97 Add typecasting to bigint array
  Makefile
  postgraph--0.0.1.sql
  regress/expected/agtype.out
  regress/expected/catalog.out
  regress/sql/agtype.sql
  src/backend/utils/adt/agtype.c
  src/backend/utils/adt/agtype_typecasting.c
Labels: enhancement, maintenance

#109 Moved int4 typecasting and standardized typecasting
  src/backend/utils/adt/agtype.c
  src/backend/utils/adt/agtype_typecasting.c
Labels: maintenance

#110 Standardized string typecasting
  regress/expected/expr.out
  src/backend/utils/adt/agtype.c
  src/backend/utils/adt/agtype_typecasting.c
Labels: maintenance

#111 Standardized int2, float8 and numeric typecasting
  src/backend/utils/adt/agtype.c
  src/backend/utils/adt/agtype_typecasting.c
  src/include/utils/agtype.h
Labels: maintenance

#287 add Github issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/question.md
  .github/ISSUE_TEMPLATE/question.yml
Labels: documentation, enhancement, maintenance

#289 add license to README
  README.md
Labels: documentation

#301 Update Dockerfile and dependent files
  Dockerfile
  docker-entrypoint-initdb.d/00-create-extension-postgraph.sql
Labels: bug, enhancement

#303 Remove the EXPLAIN keywords from Grammar
  src/backend/parser/cypher_gram.y
  src/include/parser/cypher_kwlist.h
Labels: bug, maintenance

#304 Remove Bulk Loader
  Makefile
  postgraph--0.0.1.sql
  regress/age_load/data/cities.csv
  regress/age_load/data/countries.csv
  regress/age_load/data/edges.csv
  regress/expected/catalog.out
  regress/expected/index.out
  regress/sql/age_load.sql
  regress/sql/index.sql
  src/backend/utils/load/ag_load_edges.c
  src/backend/utils/load/ag_load_labels.c
  src/backend/utils/load/age_load.c
  src/backend/utils/load/libcsv.c
Labels: bug, maintenance

#307 Remove VLE Cacheing Mechanic
  postgraph--0.0.1.sql
  regress/expected/catalog.out
  regress/expected/cypher_vle.out
  regress/expected/expr.out
  regress/sql/cypher_vle.sql
  regress/sql/expr.sql
  src/backend/parser/cypher_clause.c
  src/backend/parser/cypher_gram.y
  src/backend/utils/adt/age_global_graph.c
  src/backend/utils/adt/age_vle.c
  src/backend/utils/adt/agtype.c
  src/include/utils/age_vle.h
Labels: enhancement, maintenance

#308 Timestamp datatype
  postgraph--0.0.1.sql
  regress/expected/agtype.out
  regress/expected/catalog.out
  regress/expected/expr.out
  regress/sql/agtype.sql
  regress/sql/expr.sql
  src/backend/parser/cypher_expr.c
  src/backend/utils/adt/agtype.c
  src/backend/utils/adt/agtype_ext.c
  src/backend/utils/adt/agtype_typecasting.c
  src/include/utils/agtype.h
  src/include/utils/agtype_parser.h
Labels: enhancement

#309 Implement Route Datatype
  Makefile
  postgraph--0.0.1.sql
  regress/expected/catalog.out
  regress/expected/route.out
  regress/sql/route.sql
  src/backend/utils/adt/edge.c
  src/backend/utils/adt/route.c
  src/backend/utils/adt/vertex.c
  src/include/utils/edge.h
  src/include/utils/route.h
  src/include/utils/vertex.h
Labels: enhancement

#313 Count agg
  postgraph--0.0.1.sql
  regress/expected/catalog.out
Labels: enhancement, maintenance
